# Generated by Django 4.1.7 on 2023-08-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hiringPlatform", "0002_jobrole_userrole_delete_jobmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrole",
            name="title",
        ),
        migrations.AddField(
            model_name="userrole",
            name="current_CTC",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userrole",
            name="expected_CTC",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userrole",
            name="location_pref",
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.CreateModel(
            name="CompanyRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("offered_CTC", models.IntegerField(default=0)),
                ("location", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hiringPlatform.jobrole",
                    ),
                ),
            ],
        ),
    ]
